imports:
    - { resource: "%kernel.root_dir%/config/parameters.ini" }

zeega.parsers:
    google.com:
        item_parser:
            regex: /http:\/\/(?:books\.)?google.com\/books\?id=([a-zA-Z0-9\-_]+)/
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\GoogleBook\ParserGoogleBook
    flickr.com:
        item_parser:
            regex: "#https?://(?:www\.)?flickr\.com/photos/[^/]+/([0-9]+)#"
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\Flickr\ParserFlickrPhoto
            parameters:
                authentication_key: %flickr_key%
        set_parser:
            regex: "#https?://(?:www\.)?flickr\.com/photos/[^/]+/sets/([0-9]+)#"
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Flickr\ParserFlickrSet
            parameters:
                authentication_key: %flickr_key%
        tag_parser:
            regex: "#https?://(?:www\.)?flickr\.com/photos/.*/tags/([a-zA-Z0-9\-_]+)#"
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Flickr\ParserFlickrTag
            parameters:
                authentication_key: %flickr_key%
    facebook.com:
        item_parser:
            regex: /https?:\/\/(?:www\.)?facebook.com\/photo.php\?fbid=([0-9]+)&set=([a-zA-Z0-9]+).([0-9]+).([0-9]+).([0-9]+)*/
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\Facebook\ParserFacebookPhoto
        set_parser:
            regex: /https?:\/\/(?:www\.)?facebook.com\/media\/set\/\?set=([a-zA-Z0-9]+).([0-9]+).([0-9]+).([0-9]+)*/
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Facebook\ParserFacebookSet

    #dropbox.com:
    #    set_parser:
    #        regex: /https?:\/\/(?:www\.)?www.dropbox.com\/home\/Apps\/Zeega/
    #        is_set: true
    #        parser_class: Zeega\IngestionBundle\Parser\Dropbox\ParserDropboxSet

    instagram.com:
        item_parser:
            regex: "#https?://instagram\.com/p/([a-zA-Z0-9\-_]+)/?#"
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\Instagram\ParserInstagramItem

        tag_parser:
            regex: /instagram-tag-parser/
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Instagram\ParserInstagramTag

    youtube.com:
        item_parser:
            regex: /https?:\/\/(?:www\.)?youtube.*watch\?v=([a-zA-Z0-9\-_]+)/
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\Youtube\ParserYoutubeVideo
        set_parser:
            regex: /https?:\/\/(?:www\.)?youtube.*list=([a-zA-Z0-9\-_]+)+/
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Youtube\ParserYoutubePlaylist
        set_parser2:
            regex: /https?:\/\/(?:www\.)?youtube.com\/p\/([a-zA-Z0-9\-_]+)/
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Youtube\ParserYoutubePlaylist
        tag_parser:
            regex: /https?:\/\/(?:www\.)?youtubeeee.com\/p\/([a-zA-Z0-9\-_]+)/
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Youtube\ParserYoutubeTag
            
    soundcloud.com: #order matters (last regex matches any soundlcoud url)
        item_parser:
            regex: /https?:\/\/(?:www\.)?soundcloud.com.*\/sets\/.*/
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Soundcloud\ParserSoundcloudSet
        set_parser:
            regex: /https?:\/\/(?:www\.)?soundcloud.com.*/
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\Soundcloud\ParserSoundcloudItem
        tag_parser:
            regex: /https?:\/\/(?:www\.)?soundcloud.com/impossibleregex/
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\Soundcloud\ParserSoundcloudTag
    dp.la:
        set_parser:
            regex: /http:\/\/(?:api\.)?dp.la\/.*/
            is_set: true
            parser_class: Zeega\IngestionBundle\Parser\DPLA\ParserDPLASet
    mapbox.com:
        item_parser:
            regex: "#https?:\/\/(?:tiles\.)?mapbox.*\/([^/]+/map/[^/]+)\##"
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\Mapbox\ParserMapboxTiles
    #vimeo.com:
       # item_parser:
         #   regex: /http:\/\/(?:www\.)?vimeo.com.*\/([a-zA-Z0-9\-_]+)/
         #   is_set: false
         #   parser_class: Zeega\IngestionBundle\Parser\Vimeo\ParserVimeoVideo
    archive.org:
        item_parser:
            regex: /http:\/\/(?:www\.)?archive.org\/details.*/
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\InternetArchive\ParserInternetArchive
    documentcloud.org:
        item_parser:
            regex: /http:\/\/(?:www\.)?documentcloud.org\/documents.*/
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\DocumentCloud\ParserDocumentCloud

    tumblr.com:
        item_parser:
            regex: /http:\/\/([a-zA-Z0-9\-_]+).tumblr.com\/post\/([a-zA-Z0-9\-_]+)/
            is_set: false
            parser_class: Zeega\IngestionBundle\Parser\Tumblr\ParserTumblr
