parameters:
#    zeega_social.example.class: Zeega\SocialBundle\Example

services:
#    zeega_social.example:
#        class: %zeega_social.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
